version: "2"
services:
  haproxy:
    image: eeacms/haproxy
    depends_on:
    - webapp
    ports:
    - "80:8080"
    - "1936:1936"
    environment:
      FRONTEND_PORT: "8080"
      BACKENDS: "webapp"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "True"
      HTTPCHK: "GET /"
      INTER: "5s"
      LOG_LEVEL: "info"
      #USE_HTTPS: "True" Uncomment this to binding https
      #CERT_FILE: "/etc/haproxy/certs/cert.pem" Uncomment this if you want to copy to another directory within container
  webapp:
    image: eeacms/hello
    environment:
      PORT: "8080"
